"""empty message

Revision ID: 9206364cc942
Revises: 6f8c009bc96f
Create Date: 2018-04-18 17:07:58.256045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9206364cc942'
down_revision = '6f8c009bc96f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('gravatar_hash', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'gravatar_hash')
    # ### end Alembic commands ###
