"""empty message

Revision ID: ba3628f067ad
Revises: 66a1f398df49
Create Date: 2018-04-10 17:15:58.568128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba3628f067ad'
down_revision = '66a1f398df49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    op.drop_column('users', 'comfirmed')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('comfirmed', sa.BOOLEAN(), nullable=True))
    op.drop_column('users', 'confirmed')
    # ### end Alembic commands ###
